// Add language options array
export const languageOptions = [
  { value: "english", label: "English", native: "English" },
  { value: "hindi", label: "Hindi", native: "हिंदी" },
  { value: "chinese", label: "Chinese", native: "中文" },
  { value: "japanese", label: "Japanese", native: "日本語" },
  { value: "korean", label: "Korean", native: "한국어" },
  { value: "arabic", label: "Arabic", native: "العربية" },
  { value: "russian", label: "Russian", native: "Русский" },
  { value: "thai", label: "Thai", native: "ไทย" },
  { value: "vietnamese", label: "Vietnamese", native: "Tiếng Việt" },
  { value: "bengali", label: "Bengali", native: "বাংলা" },
  { value: "tamil", label: "Tamil", native: "தமிழ்" },
  { value: "telugu", label: "Telugu", native: "తెలుగు" },
  { value: "marathi", label: "Marathi", native: "मराठी" },
  { value: "gujarati", label: "Gujarati", native: "ગુજરાતી" },
  { value: "kannada", label: "Kannada", native: "ಕನ್ನಡ" },
  { value: "malayalam", label: "Malayalam", native: "മലയാളം" },
  { value: "punjabi", label: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { value: "urdu", label: "Urdu", native: "اردو" },
  { value: "persian", label: "Persian", native: "فارسی" },
  { value: "greek", label: "Greek", native: "Ελληνικά" },
  { value: "hebrew", label: "Hebrew", native: "עברית" },
  { value: "turkish", label: "Turkish", native: "Türkçe" },
  { value: "portuguese", label: "Portuguese", native: "Português" },
  { value: "spanish", label: "Spanish", native: "Español" },
  { value: "french", label: "French", native: "Français" },
  { value: "german", label: "German", native: "Deutsch" },
  { value: "italian", label: "Italian", native: "Italiano" },
  { value: "dutch", label: "Dutch", native: "Nederlands" },
  { value: "polish", label: "Polish", native: "Polski" },
  { value: "czech", label: "Czech", native: "Čeština" },
  { value: "swedish", label: "Swedish", native: "Svenska" },
  { value: "danish", label: "Danish", native: "Dansk" },
  { value: "norwegian", label: "Norwegian", native: "Norsk" },
  { value: "finnish", label: "Finnish", native: "Suomi" },
  { value: "hungarian", label: "Hungarian", native: "Magyar" },
  { value: "romanian", label: "Romanian", native: "Română" },
  { value: "bulgarian", label: "Bulgarian", native: "Български" },
  { value: "ukrainian", label: "Ukrainian", native: "Українська" },
  { value: "indonesian", label: "Indonesian", native: "Bahasa Indonesia" },
  { value: "malay", label: "Malay", native: "Bahasa Melayu" },
  { value: "tagalog", label: "Filipino", native: "Filipino" },
  { value: "swahili", label: "Swahili", native: "Kiswahili" },
];
